# only for development, never use it in prod

services:
  postgres:
    image: postgres:16
    container_name: survey-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: survey
      POSTGRES_USER: survey_user
      POSTGRES_PASSWORD: survey_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
